# Generated by Django 3.1.2 on 2020-10-05 10:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SampleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('DJ', 'Django'), ('LI', 'Linux'), ('OR', 'Oracle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ID', 'Indore'), ('SWD', 'Sendhwa'), ('HYD', 'Hyderabad'), ('DH', 'Delhi')], max_length=100),
        ),
    ]
